In [9]:
import math
import numpy as np

# Question - 1

In [10]:
A=np.matrix([[1,2,3],[2,1,4]])
B=np.matrix([[1,0],[2,1],[3,2]])
C=np.matrix([[3,-1,3],[4,1,5],[2,1,3]])
D=np.matrix([[2,-4,5],[0,1,4],[3,2,1]])
E=np.matrix([[3,-2],[2,4]])


In [11]:
a=2*A
print(a,"\n")

#b=(A-B).T

c=((3*B).T - A).T
print(c,"\n")

d=((-A).T)*E
print(d,"\n")

#e= (C + 2*(D.T) + E).T


[[2 4 6]
 [4 2 8]] 

[[ 2 -2]
 [ 4  2]
 [ 6  2]] 

[[ -7  -6]
 [ -8   0]
 [-17 -10]] 



# Question - 2

In [12]:
A=np.matrix([[1,4],[3,2]])
B=np.matrix([[2,-1],[-3,4]])
print(A*B)
print(B*A)

print( A*B == B*A )




[[-10  15]
 [  0   5]]
[[-1  6]
 [ 9 -4]]
[[False False]
 [False False]]


# Question - 3


In [13]:
V1=np.array([1,0,-1])
V2=np.array([1,round(math.sqrt(2),2),1])
V3=np.array([1,-round(math.sqrt(2),2),1])

print("V1: ",V1,"\n", "V2: ",V2,"\n","V3: ",V3)

V1:  [ 1  0 -1] 
 V2:  [1.   1.41 1.  ] 
 V3:  [ 1.   -1.41  1.  ]


In [14]:
print(f'V1 dot V2 is ', np.dot(V1,V2))
print(f'V2 dot V3 is ', round(np.dot(V2,V3),1))
print(f'V1 dot V3 is ', np.dot(V1,V3))


print("since V1•V2 = V1•V3 = V2•V3 = 0 , They form Orthogonal Set ") 
print("For Orthonormal Sets each of V1, V2, V3 should be unit vector which we can do by normalizing them ")

V1 = V1 / np.linalg.norm(V1)
V2 = V2 / np.linalg.norm(V2)
V3 = V3 / np.linalg.norm(V3)

print("V1: ",V1,"\n", "V2: ",V2, "\n","V3: ",V3)

V1 dot V2 is  0.0
V2 dot V3 is  0.0
V1 dot V3 is  0.0
since V1•V2 = V1•V3 = V2•V3 = 0 , They form Orthogonal Set 
For Orthonormal Sets each of V1, V2, V3 should be unit vector which we can do by normalizing them 
V1:  [ 0.70710678  0.         -0.70710678] 
 V2:  [0.50074541 0.70605103 0.50074541] 
 V3:  [ 0.50074541 -0.70605103  0.50074541]


# Question - 4


In [15]:
print("Given X belongs to m dimension & \n Y belongs to n dimension")

np.random.seed(2024) 

X = np.random.randint(low=1, high=5, size=(4, 1))
Y = np.random.randint(1, 5, (5, 1))
print(X,"\n")
print(Y,"\n")
res=X*((Y).T)
print(res,"\n")

print("Rank of Resultant Matrix :",np.linalg.matrix_rank(res))



Given X belongs to m dimension & 
 Y belongs to n dimension
[[1]
 [3]
 [1]
 [1]] 

[[4]
 [1]
 [3]
 [4]
 [2]] 

[[ 4  1  3  4  2]
 [12  3  9 12  6]
 [ 4  1  3  4  2]
 [ 4  1  3  4  2]] 

Rank of Resultant Matrix : 1


# Question - 5


In [20]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([4,5,6,8])
d = np.dot(a,b)
n = 4
e = 0
for i in range(n):
    e = np.dot(a[i],b[i]) + e
if(np.array_equal(d,e)):
    print("It is equal.")
else:
    print("It is not equal.")
print("Result: ",e)


It is equal.
Result:  64


# Question - 6


In [19]:
X = np.random.randint(low=1, high=5, size=(5, 5))
X_T = X.T
c = X_T * X

# symmetric or not 
if(c.all() == (c.T).all()):
    print("Xt * X is Symmetric")
else :
    print("Xt * X is NOT Symmetric")

Eig_Val, Eig_Vect = np.linalg.eig(X)
if(Eig_Val.all()>=0):
    print("All Eigen_Values are greater or equal to 0 hence it is postive semi definite.")
else: 
    print("It is not.")

Xt * X is Symmetric
All Eigen_Values are greater or equal to 0 hence it is postive semi definite.


# Question - 7

In [ ]:
from sympy import symbols, exp, log, diff

x, y = symbols('x y')
g = exp(x) + exp(y) + exp(-2*x*y) - log(-x**2*y)
g_x = diff(g, x)
g_y = diff(g, y)
print(g_x,"\n")
print(g_y)

-2*y*exp(-2*x*y) + exp(x) - 2/x 

-2*x*exp(-2*x*y) + exp(y) - 1/y


# Question - 8

In [ ]:
A =np.matrix("2 1 3; 1 1 2; 3 2 5 ")

w,v = np.linalg.eig(A)

print(np.round(w,3)," \n")

print(v," \n")


print (" Determinant of Matrix is ",round(np.linalg.det(A))," \n")
print (" Rank of Matrix is ",round(np.linalg.matrix_rank(A))," \n")


print("Is matrix positive definite: YES") if (np.all(np.round(np.linalg.eigvals(A),2) > 0)) else print("Is matrix positive definite: NO")
print("Is matrix positive semi definite: YES") if (np.all(np.round(np.linalg.eigvals(A),2) >= 0)) else print("Is matrix positive  semi definite: NO")


Λ = np.diag(np.round(w,2))
print("Diagonal Matrix of A is : \n\n Λ =\n ",Λ)
print("\n\n\n\n")

U = np.round(v,2)
print("U Matrix of A is : \n\n U =\n ",U)
print("\n\n\n\n")

Uinv = np.linalg.inv(U)
print(f"U^ -1 Matrix of A is : \n\n U^-1  =\n ",Uinv)

print("\n\n\n\n")

print( f"Eigen vector corresponding to {w[0]} is \n {v[:,0]} \n" )
print( f"Eigen vector corresponding to {w[1]} is \n {v[:,1]} \n" )
print( f"Eigen vector corresponding to {w[1]} is \n {v[:,2]} \n" )




[7.606 0.394 0.   ]  

[[-0.49079864 -0.65252078 -0.57735027]
 [-0.31970025  0.75130448 -0.57735027]
 [-0.81049889  0.0987837   0.57735027]]  

 Determinant of Matrix is  0  

 Rank of Matrix is  2  

Is matrix positive definite: NO
Is matrix positive semi definite: YES
Diagonal Matrix of A is : 

 Λ =
  [[7.61 0.   0.  ]
 [0.   0.39 0.  ]
 [0.   0.   0.  ]]





U Matrix of A is : 

 U =
  [[-0.49 -0.65 -0.58]
 [-0.32  0.75 -0.58]
 [-0.81  0.1   0.58]]





U^ -1 Matrix of A is : 

 U^-1  =
  [[-0.49232551 -0.31856357 -0.81088908]
 [-0.65450333  0.75296843  0.0984651 ]
 [-0.57471264 -0.57471264  0.57471264]]





Eigen vector corresponding to 7.6055512754639905 is 
 [[-0.49079864]
 [-0.31970025]
 [-0.81049889]] 

Eigen vector corresponding to 0.39444872453601054 is 
 [[-0.65252078]
 [ 0.75130448]
 [ 0.0987837 ]] 

Eigen vector corresponding to 0.39444872453601054 is 
 [[-0.57735027]
 [-0.57735027]
 [ 0.57735027]] 

